name: HELLO-WORK-FLOW
concurrency:
  # Group PRs by head_ref, push to main branch by commit id, and others branch by ref.
  group: ${{ github.workflow }}-${{ github.head_ref || (github.ref == 'refs/heads/main' && github.sha) || github.ref }}
  cancel-in-progress: true
on:
    push:
        branches-ignore:
            - 'dependabot/**'
    pull_request:
        types: [closed, opened, synchronize, reopened]
        branches:
            - '*'
permissions:
    contents: read

jobs:
    HELLO-FIRST-JOB:
        if: >-
            github.event.action != 'closed'
        runs-on: ubuntu-20.04
        timeout-minutes: 20
        strategy:
            fail-fast: false
        steps:
          - uses: actions/checkout@v3
          - name: 'Print Current working directory'
            run: echo '${{ toJSON(github) }}'
          - name: 'Printing the workspace content'
            run: ls -ltr ${{ github.workspace }}
          - run: mkdir test1 && cd test1 && pwd
          - run: pwd
            if: >-
                !contains(github.event.head_commit.message, '[ci skip]') &&
                !contains(github.event.head_commit.message, '[skip ci]') &&
                !contains(github.event.pull_request.title, '[skip ci]') &&
                !contains(github.event.pull_request.title, '[ci skip]') &&
                (github.event.pull_request.draft == false || !contains(github.event.pull_request.labels.*.name, 'pr: skip-ci'))
