name: HELLO-WORK-FLOW
on:
    push:
        branches-ignore:
            - 'dependabot/**'
    pull_request:
        types: [closed, opened, synchronize, reopened]
        branches:
            - '*'
permissions:
    contents: read

jobs:
    HELLO-FIRST-JOB:
        if: >-
            github.event.action != 'closed'
        runs-on: ubuntu-20.04
        timeout-minutes: 20
        strategy:
            fail-fast: false
        steps:
          - uses: actions/checkout@v3
          - name: 'Print Current working directory'
            run: echo '${{ toJSON(github) }}'
          - name: 'Printing the workspace content'
            run: ls -ltr ${{ github.workspace }}
          - run: mkdir test1 && cd test1 && pwd
          - run: pwd
